
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author donov
 */
public class FlashCards extends javax.swing.JFrame {

    /**
     * Creates new form FlashCards
     */
    
    //0 = Question ... side = 1 = Answer
    private ArrayList <Cards> flashCards = new ArrayList<Cards>();
    //used to hold filtered out cards
    RevistCards filter = new RevistCards();
    //private ArrayList <Cards> filter = new ArrayList<Cards>();
    //an index to keep track which card we're looking at
    private int cardCount = 0;
    boolean isFlipped = false;
    //reference to quiz window to be sent to cardMaker window
    private FlashCards ref;
    
    public FlashCards() {
        initComponents();
        //makeCardList();
       this.clearDisplayFrame();
    }
    //Since the display and maker frames share an ArrayList, this clears and resets the frame
    //that displays the flashcards
    private void clearDisplayFrame()
    {
       cardNumLabel.setVisible(false);
       nextBtn.setVisible(false);
       prevBtn.setVisible(false);
       flashCardBtn.setText("");
       cardCount=0;
       flashCards.clear();
    }

    private void clearRevisit()
    {
        revistChk.setSelected(false);
        showRevisitOnlyChk.setSelected(false);
    }
    public void checkVis()
    {
      //hides next button if at end of list so user doesn't go out of bounds
      if(cardCount == flashCards.size()-1)
      {
        nextBtn.setVisible(false);
      }
      else
      {
        nextBtn.setVisible(true);
      }
      
      //hides previous button if at start of list so user doesn't go out of bounds
      if(cardCount == 0)
      {
        prevBtn.setVisible(false);
      }
      else
      {
        prevBtn.setVisible(true);
      }
    }
    
    public void showCard(int side, Cards currentCard)
    {
        revistChk.setSelected(currentCard.isMarked());
        flashCardBtn.setText(currentCard.getSide(side));
        cardNumLabel.setText(currentCard.getCardNum() + "/" + flashCards.size());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saveFileFrame = new javax.swing.JFrame();
        openFileFrame = new javax.swing.JFrame();
        prevBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        cardNumLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        flashCardBtn = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        markedCardsMnu = new javax.swing.JMenu();
        revistChk = new javax.swing.JCheckBoxMenuItem();
        markedCardRevistMnu = new javax.swing.JMenu();
        showRevisitOnlyChk = new javax.swing.JCheckBoxMenuItem();
        cardMaker = new javax.swing.JMenu();
        cardMakerItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();

        saveFileFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        saveFileFrame.setTitle("Export");
        saveFileFrame.setAlwaysOnTop(true);

        javax.swing.GroupLayout saveFileFrameLayout = new javax.swing.GroupLayout(saveFileFrame.getContentPane());
        saveFileFrame.getContentPane().setLayout(saveFileFrameLayout);
        saveFileFrameLayout.setHorizontalGroup(
            saveFileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        saveFileFrameLayout.setVerticalGroup(
            saveFileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        openFileFrame.setAlwaysOnTop(true);

        javax.swing.GroupLayout openFileFrameLayout = new javax.swing.GroupLayout(openFileFrame.getContentPane());
        openFileFrame.getContentPane().setLayout(openFileFrameLayout);
        openFileFrameLayout.setHorizontalGroup(
            openFileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        openFileFrameLayout.setVerticalGroup(
            openFileFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        prevBtn.setText("Previous");
        prevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevBtnActionPerformed(evt);
            }
        });

        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        cardNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardNumLabel.setText("0/0");

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        flashCardBtn.setEditable(false);
        flashCardBtn.setColumns(20);
        flashCardBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        flashCardBtn.setLineWrap(true);
        flashCardBtn.setRows(5);
        flashCardBtn.setWrapStyleWord(true);
        flashCardBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        flashCardBtn.setFocusable(false);
        flashCardBtn.setMargin(new java.awt.Insets(35, 35, 35, 35));
        flashCardBtn.setRequestFocusEnabled(false);
        flashCardBtn.setVerifyInputWhenFocusTarget(false);
        flashCardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                flashCardBtnMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(flashCardBtn);

        jMenu1.setText("File");

        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(openMenuItem);

        jMenuBar1.add(jMenu1);

        markedCardsMnu.setText("Mark Cards");

        revistChk.setText("Check For Revisiting");
        revistChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revistChkActionPerformed(evt);
            }
        });
        markedCardsMnu.add(revistChk);

        markedCardRevistMnu.setText("Revist Marked Cards");

        showRevisitOnlyChk.setText("Show Marked Cards Only");
        showRevisitOnlyChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRevisitOnlyChkActionPerformed(evt);
            }
        });
        markedCardRevistMnu.add(showRevisitOnlyChk);

        markedCardsMnu.add(markedCardRevistMnu);

        jMenuBar1.add(markedCardsMnu);

        cardMaker.setText("Options");

        cardMakerItem.setText("Make Flash Cards");
        cardMakerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardMakerItemActionPerformed(evt);
            }
        });
        cardMaker.add(cardMakerItem);

        jMenuItem1.setText("Randomize Cards");
        cardMaker.add(jMenuItem1);

        jMenu2.setText("Sort");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Ascending");
        jMenu2.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Descending");
        jMenu2.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("Marked Cards First");
        jMenu2.add(jRadioButtonMenuItem3);

        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("Marked Cards Second");
        jMenu2.add(jRadioButtonMenuItem4);

        cardMaker.add(jMenu2);

        jMenu3.setText("Timer");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Active");
        jMenu3.add(jCheckBoxMenuItem1);

        cardMaker.add(jMenu3);

        jMenuBar1.add(cardMaker);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prevBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(cardNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prevBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevBtnActionPerformed
        // TODO add your handling code here:
        --cardCount;
        //resets isFlipped variable to reflect that the question should be showing for new card
        isFlipped = false;
        showCard(0, flashCards.get(cardCount));
        checkVis();
    }//GEN-LAST:event_prevBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        ++cardCount;
        //resets isFlipped variable to reflect that the question should be showing for new card
        isFlipped = false;
        showCard(0, flashCards.get(cardCount));
        checkVis();
    }//GEN-LAST:event_nextBtnActionPerformed

    private void flashCardBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flashCardBtnMousePressed
        // TODO add your handling code here:
        if(isFlipped)
        {
            isFlipped = false;
            if(!flashCards.isEmpty())
            {
                showCard(0, flashCards.get(cardCount));
            }           
        }
        else
        {
            isFlipped = true;
             if(!flashCards.isEmpty())
            {
                 showCard(1, flashCards.get(cardCount));
            }          
        }
    }//GEN-LAST:event_flashCardBtnMousePressed

    //makes class window object same as the local window object in main 
    //so it can be referenced and passed to cardMaker class/frame
    public void setRef(FlashCards mainObject)
    {
        ref = mainObject;
    }
    //opens the frame that will allow a user to make and save flash cards
    private void cardMakerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardMakerItemActionPerformed
        // TODO add your handling code here:
        //creates an object for the card maker class to open the frame to make cards
        CardMaker myCards = new CardMaker();
        //passing a refernce to CardMaker Class back to this class
        myCards.setWindowRef(ref);
        //opening the CardMaker
        myCards.setVisible(true);
         //instead of closing it, make it so user can't use flashcards till cardMaker frame closes
        this.setEnabled(false);
    }//GEN-LAST:event_cardMakerItemActionPerformed

    //to bring back functionality of window once CardMaker window/class closes
    public void resetEnable()
    {
        this.setEnabled(true);
    }
    //lets the user locate and find a file to be opened and then calls the readFile method to put String data
    //formatted by the saveFile methodinto the ArrayList
    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
        //reset the cards before loading in the new set
        
        JFileChooser fileLoad = new JFileChooser("E:\\Quizlet FlashCard Files");
        int selection = fileLoad.showOpenDialog(openFileFrame);
        if(selection == JFileChooser.APPROVE_OPTION)
        {
            this.clearDisplayFrame();
            this.clearRevisit();
            filter.resetFilter();
            readFile(fileLoad.getSelectedFile());
            checkVis();
            cardNumLabel.setVisible(true);
            showCard(0,flashCards.get(0));
            filter.setFilter(flashCards);
        }          
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void revistChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revistChkActionPerformed
        // TODO add your handling code here:
        
        if(flashCards.isEmpty())
        {
            revistChk.setSelected(false);          
        }
        else if(showRevisitOnlyChk.isSelected())
        {
            revistChk.setSelected(true);
        }
        else
        {
            flashCards.get(cardCount).setMarked(revistChk.isSelected());
            filter.getCardRef(flashCards, cardCount).setMarked(revistChk.isSelected());
        }
    }//GEN-LAST:event_revistChkActionPerformed

    public void updateDisplay()
    {
        this.checkVis();
        cardNumLabel.setVisible(true);
        this.showCard(0, flashCards.get(0));
    }
    
    private void showRevisitOnlyChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRevisitOnlyChkActionPerformed
        // TODO add your handling code here:
        //check if user wants only the marked cards
        
        if(!filter.anyMarked())
        {
            showRevisitOnlyChk.setSelected(false);
        }
        else if(showRevisitOnlyChk.isSelected() && !flashCards.isEmpty())
        {
            this.clearDisplayFrame();
            //filter out all non marked cards from flashCards          
            filter.filterUnmarkedCards(flashCards); 
            this.updateDisplay();
        }
        else if(!showRevisitOnlyChk.isSelected())
        {           
                this.clearDisplayFrame();
                flashCards.addAll(filter.getFilter());              
               //resets card numbers for when marked only mode is turned off
               filter.resetCardNumbering(flashCards);
               this.updateDisplay();           
        }
        else
        {
            showRevisitOnlyChk.setSelected(false);
        }
                  
    }//GEN-LAST:event_showRevisitOnlyChkActionPerformed

    private void readFile(File selectedFile) 
    {    
        try {
            BufferedReader reader = new BufferedReader(new FileReader(selectedFile));
            String question = reader.readLine();
            String answer = "";
            int seperator = 0;
            while (question != null) {
                for(int i=0; i < question.length(); ++i)
                {
                    if(question.charAt(i) == '/')
                    {
                        seperator = i;
                        i=question.length();                        
                    }
                }
                    answer = question.substring((seperator+1));  
                    question = question.substring(0, (seperator-1));
                    flashCards.add(new Cards(question, answer));
                    flashCards.get(flashCards.size()-1).setCardNum(flashCards.size());
                    question = reader.readLine();
                }
                reader.close();
            } catch (Exception e) {
                //System.out.println("Error: Couldn't read to file.");
                JOptionPane.showMessageDialog(null, "Error: Couldn't read file.", "Error", JOptionPane.ERROR_MESSAGE);
            }        
    }
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlashCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlashCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlashCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlashCards.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FlashCards myWindow = new FlashCards();
                myWindow.setRef(myWindow);
                myWindow.setVisible(true);             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu cardMaker;
    private javax.swing.JMenuItem cardMakerItem;
    private javax.swing.JLabel cardNumLabel;
    private javax.swing.JTextArea flashCardBtn;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu markedCardRevistMnu;
    private javax.swing.JMenu markedCardsMnu;
    private javax.swing.JButton nextBtn;
    private javax.swing.JFrame openFileFrame;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JButton prevBtn;
    private javax.swing.JCheckBoxMenuItem revistChk;
    private javax.swing.JFrame saveFileFrame;
    private javax.swing.JCheckBoxMenuItem showRevisitOnlyChk;
    // End of variables declaration//GEN-END:variables
}
